# -*- coding: utf-8 -*-
"""EvaluaciónSumativaDesarrollo-JuanMorillo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0_BnXTKykX4I_diG0ou0P6St0cWiZrF

Juan Pablo Morillo Macias
"""

import pandas as pd
import ssl

ssl._create_default_hhtps_context=ssl._create_unverified_context

"""  1"""

import pandas as pd

# Leer todas las tablas de la página
url = "https://en.wikipedia.org/wiki/List_of_Latin_phrases_(full)"
tables = pd.read_html(url)

# Normalizar las tablas y unirlas
tablas_limpias = []
for i, df in enumerate(tables):
    df.columns = df.columns.tolist()  # Asegura que las columnas estén correctamente asignadas
    tablas_limpias.append(df)

# Concatenar todas las tablas en un solo DataFrame
df_unido = pd.concat(tablas_limpias, ignore_index=True)

# Mostrar algunas filas del DataFrame unido
df_unido.head()

"""2"""

nombre_archivo = "frases_latinas.xlsx"
df_unido.to_excel(nombre_archivo, index=False)

print(f"Archivo guardado como '{nombre_archivo}'")

"""3"""

import pandas as pd
import spacy
from collections import Counter

# Cargar modelo SpaCy en español
nlp = spacy.load("it_core_news_sm")


# Inicializar el contador
contador_nouns = Counter()

# Procesar todos los textos y contar los sustantivos
for texto in df_unido['Latin']:
    doc = nlp(str(texto))
    nouns = [token.lemma_ for token in doc if token.pos_ == 'NOUN']
    contador_nouns.update(nouns)


# Obtener el sustantivo más repetido
mas_repetida = contador_nouns.most_common(1)[0]
print("Sustantivo más repetido en latín:")
print(f"{mas_repetida[0]} (repetido {mas_repetida[1]} veces)")

import pandas as pd
import spacy
from collections import Counter

# Cargar modelo SpaCy en español
nlp = spacy.load("it_core_news_sm")


# Inicializar el contador
contador_nouns = Counter()

# Procesar todos los textos y contar los sustantivos
for texto in df_unido['Latin']:
    doc = nlp(str(texto))
    nouns = [token.lemma_ for token in doc if token.pos_ == 'VERB']
    contador_nouns.update(nouns)

# Obtener el sustantivo más repetido
mas_repetida = contador_nouns.most_common(1)[0]
print("Verbo más repetido en latín:")
print(f"{mas_repetida[0]} (repetido {mas_repetida[1]} veces)")

nlp = spacy.load("en_core_web_sm")

contador_nouns = Counter()

# Procesar todos los textos y contar los sustantivos
for texto in df_unido['Translation']:
    doc = nlp(str(texto))
    nouns = [token.lemma_ for token in doc if token.pos_ == 'NOUN']
    contador_nouns.update(nouns)


# Obtener el sustantivo más repetido
mas_repetida = contador_nouns.most_common(1)[0]
print("Sustantivo más repetido en inglés:")
print(f"{mas_repetida[0]} (repetido {mas_repetida[1]} veces)")

nlp = spacy.load("en_core_web_sm")

contador_nouns = Counter()

# Procesar todos los textos y contar los sustantivos
for texto in df_unido['Translation']:
    doc = nlp(str(texto))
    nouns = [token.lemma_ for token in doc if token.pos_ == 'VERB']
    contador_nouns.update(nouns)




# Obtener el sustantivo más repetido
mas_repetida = contador_nouns.most_common(1)[0]
print("Verbo más repetido en inglés:")
print(f"{mas_repetida[0]} (repetido {mas_repetida[1]} veces)")



!pip install -U spacy

!python -m spacy download es_core_news_sm

!python -m spacy download en_core_web_sm

!python -m spacy download it_core_news_sm